services:
  frontend:
    image: ashmit1020/blog-frontend:v1.2  # Replace with the image name of your production app
    ports:
      - "80:80"  # Expose port 80 to access the app
    networks:
      - app-network

  backend:
   # build: /home/ashmit/code/kubernetes_blog_backend/  # Replace with the image name of your development app
    image: ashmit1020/blog-backend:v1
    ports:
      - "5004:5004"  # Expose port 5004 to access the dev server
    command: ["npm","start"]  # Start the development server (or any other command you use)
    networks:
      - app-network
    depends_on:
      - frontend

networks:
  app-network:
    driver: bridge



